In [2]:
#기본
import numpy as np
import pandas as pd

#전처리(인코딩)
from sklearn.preprocessing import LabelEncoder 

#전처리(스케일링)
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler

#전처리(검증 데이터 나누기)
from sklearn.model_selection import train_test_split

#모델학습
from sklearn.ensemble import RandomForestClassifier

#평가
from sklearn.metrics import f1_score

In [5]:
train = pd.read_csv('score_train.csv')
test = pd.read_csv('score_test.csv')

In [6]:
print('train :', train.shape)
print('test :', test.shape)

train : (4198, 21)
test : (1499, 20)

In [7]:
set(train) - set(test)

{'Credit_Score'}

In [8]:
#y값 분리
target = train.pop('Credit_Score')

In [9]:
train.head()

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,26.0,10.0,5.0,30.358905,200.0,NM,192.341800,321.431503,Good,Low_spent_Small_value_payments,27.0,36963.89,0.0,4.0,1.0,2.0,2902.324167,6.47,1195.96,46.459114
1,6.0,17.0,4.0,24.589796,70.0,Yes,53.110239,427.404738,Standard,High_spent_Medium_value_payments,21.0,34599.80,8.0,4.0,16.0,3.0,3130.316667,16.53,851.37,82.516689
2,29.0,16.0,6.0,39.456866,14.0,Yes,150.829491,239.039985,Bad,Low_spent_Small_value_payments,14.0,19531.18,7.0,10.0,25.0,5.0,1679.598333,20.74,3047.42,68.090357
3,14.0,6.0,2.0,28.368731,245.0,NM,76.721091,948.735499,Good,High_spent_Large_value_payments,18.0,107774.28,1.0,7.0,10.0,2.0,9142.190000,2.78,937.74,128.762410
4,9.0,10.0,4.0,25.099529,220.0,No,44.380050,446.726147,Good,High_spent_Medium_value_payments,32.0,42326.99,0.0,2.0,4.0,4.0,3577.249167,5.97,1233.00,116.618720

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4198 entries, 0 to 4197
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       4198 non-null   float64
 1   Num_of_Delayed_Payment    4198 non-null   float64
 2   Num_Credit_Inquiries      4198 non-null   float64
 3   Credit_Utilization_Ratio  4198 non-null   float64
 4   Credit_History_Age        4198 non-null   float64
 5   Payment_of_Min_Amount     4198 non-null   object
 6   Amount_invested_monthly   4198 non-null   float64
 7   Monthly_Balance           4198 non-null   float64
 8   Credit_Mix                4198 non-null   object
 9   Payment_Behaviour         4198 non-null   object
 10  Age                       4198 non-null   float64
 11  Annual_Income             4198 non-null   float64
 12  Num_Bank_Accounts         4198 non-null   float64
 13  Num_Credit_Card           4198 non-null   float64
 14  Interest_Rate             4198 non-null   float64
 15  Num_of_Loan               4198 non-null   float64
 16  Monthly_Inhand_Salary     4198 non-null   float64
 17  Changed_Credit_Limit      4198 non-null   float64
 18  Outstanding_Debt          4198 non-null   float64
 19  Total_EMI_per_month       4198 non-null   float64
dtypes: float64(17), object(3)
memory usage: 656.1+ KB

In [11]:
train.describe()

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Amount_invested_monthly,Monthly_Balance,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
count,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000,4198.000000
mean,21.363983,13.353978,5.746308,32.231895,222.225345,191.510951,404.255307,33.313721,50484.607537,5.424726,5.530729,14.578371,3.563125,4195.260793,10.357006,1409.436679,109.368995
std,14.760722,6.189640,3.853921,5.139842,99.764260,193.237278,211.622208,10.736982,38079.236375,2.555354,2.062956,8.568630,2.465621,3159.974294,6.532086,1146.835939,141.802993
min,0.000000,0.000000,0.000000,20.985606,1.000000,0.000000,8.063863,14.000000,7019.435000,0.000000,1.000000,1.000000,0.000000,357.255833,0.510000,0.540000,0.000000
25%,10.000000,9.000000,3.000000,27.990565,148.000000,71.267456,272.249521,24.000000,19558.610000,4.000000,4.000000,8.000000,2.000000,1654.409375,5.400000,546.840000,29.294379
50%,19.000000,14.000000,5.000000,32.117580,221.000000,127.766968,340.080970,33.000000,36820.590000,6.000000,5.000000,13.000000,3.000000,3088.630000,9.275000,1170.415000,68.084075
75%,28.000000,18.000000,8.000000,36.488230,302.000000,234.452093,474.931229,42.000000,71842.800000,7.000000,7.000000,20.000000,5.000000,5987.795833,14.910000,1916.575000,147.166548
max,67.000000,28.000000,17.000000,48.023249,404.000000,1733.700474,1508.926823,56.000000,179193.760000,10.000000,11.000000,34.000000,9.000000,15101.940000,29.980000,4990.910000,1779.103254

In [13]:
train.describe(include='O')

       Payment_of_Min_Amount Credit_Mix               Payment_Behaviour
count                   4198       4198                            4198
unique                     3          3                               6
top                      Yes   Standard  Low_spent_Small_value_payments
freq                    2234       1967                            1415

In [14]:
train.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [15]:
test.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

### 전처리(인코딩)

In [17]:
data = pd.concat([train, test])
data = pd.get_dummies(data)

train = data[:len(train)].copy()
test = data[len(train):].copy()

print('train :', train.shape)
print('test :', test.shape)

train : (4198, 29)
test : (1499, 29)

### 검증데이터 나누기(랜덤포레스트는 스케일링이 큰 의미를 가지지 않음으로 생략)

In [19]:
x_train,x_val,y_train,y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0,
)

print('x_train :', x_train.shape)
print('x_val :', x_val.shape)
print('y_train :', y_train.shape)
print('y_val :', y_val.shape)

x_train : (3358, 29)
x_val : (840, 29)
y_train : (3358,)
y_val : (840,)

### 머신러닝 학습

In [22]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

pred = model.predict(x_val)

#### 머신러닝 평가

In [23]:
f1 = f1_score(y_val, pred, average='micro')
print('f1_score :', f1)

f1_score : 0.7023809523809523

In [24]:
submit = pd.DataFrame({'pred':pred})
submit.to_csv('score_result.csv', index=False)

In [25]:
submit['pred'].value_counts()

pred
Standard    415
Poor        240
Good        185
Name: count, dtype: int64