In [41]:
import numpy as np
import pandas as pd

### 데이터 분석

In [42]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [43]:
print('train 행열:', train.shape)
print('test 행열:', test.shape)

train 행열: (6818, 12)
test 행열: (1705, 11)

In [44]:
train.head(2)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,NCR06,12.5,Low Fat,0.006760,Household,42.8112,OUT013,1987,High,Tier 3,Supermarket Type1,639.1680
1,FDW11,12.6,Low Fat,0.048741,Breads,60.4194,OUT013,1987,High,Tier 3,Supermarket Type1,990.7104

In [45]:
test.head(2)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDO38,17.25,Low Fat,0.073251,Canned,76.4986,OUT017,2007,NaN,Tier 2,Supermarket Type1
1,FDO32,6.36,Low Fat,0.120544,Fruits and Vegetables,45.8060,OUT046,1997,Small,Tier 1,Supermarket Type1

In [46]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818 entries, 0 to 6817
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            6818 non-null   object
 1   Item_Weight                5656 non-null   float64
 2   Item_Fat_Content           6818 non-null   object
 3   Item_Visibility            6818 non-null   float64
 4   Item_Type                  6818 non-null   object
 5   Item_MRP                   6818 non-null   float64
 6   Outlet_Identifier          6818 non-null   object
 7   Outlet_Establishment_Year  6818 non-null   int64
 8   Outlet_Size                4878 non-null   object
 9   Outlet_Location_Type       6818 non-null   object
 10  Outlet_Type                6818 non-null   object
 11  Item_Outlet_Sales          6818 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 639.3+ KB

In [47]:
train.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,5656.000000,6818.000000,6818.000000,6818.000000,6818.000000
mean,12.872703,0.066121,140.419533,1997.885890,2190.941459
std,4.651034,0.051383,62.067861,8.339795,1706.131256
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.785000,0.026914,93.610050,1987.000000,836.577700
50%,12.600000,0.053799,142.448300,1999.000000,1806.648300
75%,17.000000,0.095273,185.060150,2004.000000,3115.944000
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [48]:
train.describe(include='O')

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
count,6818,6818,6818,6818,4878,6818,6818
unique,1554,5,16,10,3,3,4
top,FDW26,Low Fat,Snack Foods,OUT046,Medium,Tier 3,Supermarket Type1
freq,9,4092,963,763,2228,2664,4474

In [49]:
train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1162
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1940
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [50]:
test.isnull().sum()

Item_Identifier                0
Item_Weight                  301
Item_Fat_Content               0
Item_Visibility                0
Item_Type                      0
Item_MRP                       0
Outlet_Identifier              0
Outlet_Establishment_Year      0
Outlet_Size                  470
Outlet_Location_Type           0
Outlet_Type                    0
dtype: int64

### 데이터 전처리

In [51]:
#데이터 유형별 컬럼 확인
str_cols = train.select_dtypes(include='object').columns

In [52]:
num_cols = train.select_dtypes(include='number').columns

In [53]:
target = train.pop('Item_Outlet_Sales')
print('train :', train.shape)
print('test :', test.shape)

train : (6818, 11)
test : (1705, 11)

### 인코딩

In [54]:
from sklearn.preprocessing import LabelEncoder

In [55]:
data = pd.concat([train,test])
print('data :', data.shape)

data : (8523, 11)

In [56]:
le = LabelEncoder()

for col in str_cols:
    data[col] = le.fit_transform(data[col])

In [57]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,1467,12.500,1,0.006760,9,42.8112,1,1987,0,2,1
1,1075,12.600,1,0.048741,1,60.4194,1,1987,0,2,1
2,450,12.800,1,0.075997,6,97.1410,1,1987,0,2,1
3,613,6.635,2,0.046351,5,37.4506,2,2007,3,1,1
4,695,13.500,2,0.125170,13,261.4910,1,1987,0,2,1

### 결측치 처리

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
train = data.iloc[:len(train)].copy()
test = data.iloc[len(train):].copy()

print('train 행열:', train.shape)
print('test 행열:', test.shape)

train 행열: (6818, 11)
test 행열: (1705, 11)

In [60]:
weight = train['Item_Weight'].min()
size = train['Outlet_Size'].mode()[0]

train['Item_Weight'] = train['Item_Weight'].fillna(weight)
train['Outlet_Size'] = train['Outlet_Size'].fillna(size)

test['Item_Weight'] = test['Item_Weight'].fillna(weight)
test['Outlet_Size'] = test['Outlet_Size'].fillna(size)

### 검증 데이터 나누기

In [65]:
x_train,x_val,y_train,y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0,
)
print('x_train :', x_train.shape)
print('x_val :', x_val.shape)
print('y_train :', y_train.shape)
print('y_val :', y_val.shape)

x_train : (5454, 11)
x_val : (1364, 11)
y_train : (5454,)
y_val : (1364,)

## 학습 및 평가

### 선형회귀

In [70]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import root_mean_squared_error

In [67]:
from sklearn.linear_model import LinearRegression

In [68]:
lr = LinearRegression()
lr.fit(x_train,y_train)

y_pred = lr.predict(x_val)

In [71]:
print('MSE :', mean_squared_error(y_val, y_pred))
print('MAE :', mean_absolute_error(y_val, y_pred))
print('R2 Score:', r2_score(y_val, y_pred))
print('RMSE :', root_mean_squared_error(y_val, y_pred))

MSE : 1283435.4854609866
MAE : 865.4166620106961
R2 Score: 0.5056194579297795
RMSE : 1132.8881169210783

### 랜덤포레스트

In [72]:
from sklearn.ensemble import RandomForestRegressor

In [77]:
rf = RandomForestRegressor(random_state=0)
rf.fit(x_train,y_train)

y_pred = rf.predict(x_val)

In [78]:
print('MSE :', mean_squared_error(y_val, y_pred))
print('MAE :', mean_absolute_error(y_val, y_pred))
print('R2 Score:', r2_score(y_val, y_pred))
print('RMSE :', root_mean_squared_error(y_val, y_pred))

MSE : 1120677.6866018097
MAE : 748.8834540439883
R2 Score: 0.5683139133485919
RMSE : 1058.6206528316977

### lightGBM

In [82]:
import lightgbm as lgb

In [83]:
model = lgb.LGBMRegressor(random_state=0, ver_bose=-1)
model.fit(x_train,y_train)

y_pred = model.predict(x_val)

[LightGBM] [Warning] Unknown parameter: ver_bose
[LightGBM] [Warning] Unknown parameter: ver_bose
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001097 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1042
[LightGBM] [Info] Number of data points in the train set: 5454, number of used features: 11
[LightGBM] [Info] Start training from score 2202.546849
[LightGBM] [Warning] Unknown parameter: ver_bose

In [84]:
print('MSE :', mean_squared_error(y_val, y_pred))
print('MAE :', mean_absolute_error(y_val, y_pred))
print('R2 Score:', r2_score(y_val, y_pred))
print('RMSE :', root_mean_squared_error(y_val, y_pred))

MSE : 1108778.2737060841
MAE : 732.9099846008004
R2 Score: 0.572897578257618
RMSE : 1052.9854100157722

### 결과제출

In [86]:
pred = model.predict(test)
pred

[LightGBM] [Warning] Unknown parameter: ver_bose

array([1194.43385592,  845.70087837, 1976.82931647, ..., 3400.46272246,
       1109.30239824, 1327.27708818])

In [87]:
submit= pd.DataFrame({'pred' : pred})
submit.to_csv('result.csv',index=False)