In [1]:
#기본
import numpy as np
import pandas as pd

#인코딩
from sklearn.preprocessing import LabelEncoder

#스케일링
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler

#데이터 분할
from sklearn.model_selection import train_test_split

#예측모델
from sklearn.ensemble import RandomForestClassifier

#평가
from sklearn.metrics import f1_score

In [5]:
train = pd.read_csv('creditcard_train.csv')
test = pd.read_csv('creditcard_test.csv')
target = train.pop('STATUS')

### 탐색적 데이터 분석

In [6]:
print("train :", train.shape)
print("test :", test.shape)

train : (25519, 18)
test : (7591, 18)

In [7]:
train.head(3)

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5010092,F,N,N,0,225000.0,Commercial associate,Secondary / secondary special,Married,House / apartment,-10304,-1682,1,0,0,0,Laborers,2.0
1,5116701,M,N,Y,1,112500.0,Commercial associate,Secondary / secondary special,Married,House / apartment,-10189,-1189,1,1,1,0,NaN,3.0
2,5069290,F,N,Y,0,270000.0,Commercial associate,Incomplete higher,Married,House / apartment,-14783,-3397,1,0,0,0,Core staff,2.0

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25519 entries, 0 to 25518
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   25519 non-null  int64
 1   CODE_GENDER          25519 non-null  object
 2   FLAG_OWN_CAR         25519 non-null  object
 3   FLAG_OWN_REALTY      25519 non-null  object
 4   CNT_CHILDREN         25519 non-null  int64
 5   AMT_INCOME_TOTAL     25519 non-null  float64
 6   NAME_INCOME_TYPE     25519 non-null  object
 7   NAME_EDUCATION_TYPE  25519 non-null  object
 8   NAME_FAMILY_STATUS   25519 non-null  object
 9   NAME_HOUSING_TYPE    25519 non-null  object
 10  DAYS_BIRTH           25519 non-null  int64
 11  DAYS_EMPLOYED        25519 non-null  int64
 12  FLAG_MOBIL           25519 non-null  int64
 13  FLAG_WORK_PHONE      25519 non-null  int64
 14  FLAG_PHONE           25519 non-null  int64
 15  FLAG_EMAIL           25519 non-null  int64
 16  OCCUPATION_TYPE      17543 non-null  object
 17  CNT_FAM_MEMBERS      25519 non-null  float64
dtypes: float64(2), int64(8), object(8)
memory usage: 3.5+ MB

In [10]:
train.isnull().sum()

ID                        0
CODE_GENDER               0
FLAG_OWN_CAR              0
FLAG_OWN_REALTY           0
CNT_CHILDREN              0
AMT_INCOME_TOTAL          0
NAME_INCOME_TYPE          0
NAME_EDUCATION_TYPE       0
NAME_FAMILY_STATUS        0
NAME_HOUSING_TYPE         0
DAYS_BIRTH                0
DAYS_EMPLOYED             0
FLAG_MOBIL                0
FLAG_WORK_PHONE           0
FLAG_PHONE                0
FLAG_EMAIL                0
OCCUPATION_TYPE        7976
CNT_FAM_MEMBERS           0
dtype: int64

In [11]:
train.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS
count,2.551900e+04,25519.000000,2.551900e+04,25519.000000,25519.000000,25519.0,25519.000000,25519.000000,25519.000000,25519.000000
mean,5.078128e+06,0.431169,1.870835e+05,-16003.397194,59675.937184,1.0,0.225518,0.295153,0.090952,2.200321
std,4.186105e+04,0.751174,1.027817e+05,4204.377534,138017.257118,0.0,0.417931,0.456120,0.287546,0.916832
min,5.008804e+06,0.000000,2.700000e+04,-25152.000000,-15661.000000,1.0,0.000000,0.000000,0.000000,1.000000
25%,5.042012e+06,0.000000,1.215000e+05,-19495.000000,-3143.000000,1.0,0.000000,0.000000,0.000000,2.000000
50%,5.069451e+06,0.000000,1.575000e+05,-15589.000000,-1540.000000,1.0,0.000000,0.000000,0.000000,2.000000
75%,5.114646e+06,1.000000,2.250000e+05,-12483.000000,-405.000000,1.0,0.000000,1.000000,0.000000,3.000000
max,5.150487e+06,19.000000,1.575000e+06,-7705.000000,365243.000000,1.0,1.000000,1.000000,1.000000,20.000000

In [12]:
train.describe(include='O')

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE
count,25519,25519,25519,25519,25519,25519,25519,17543
unique,2,2,2,5,5,5,6,18
top,F,N,Y,Working,Secondary / secondary special,Married,House / apartment,Laborers
freq,17125,15764,17219,13083,17385,17558,22771,4304

In [13]:
train['OCCUPATION_TYPE'].value_counts()

OCCUPATION_TYPE
Laborers                 4304
Core staff               2470
Sales staff              2459
Managers                 2126
Drivers                  1465
High skill tech staff     986
Accountants               869
Medicine staff            832
Cooking staff             457
Security staff            425
Cleaning staff            378
Private service staff     256
Low-skill Laborers        126
Waiters/barmen staff      120
Secretaries               107
HR staff                   61
Realty agents              61
IT staff                   41
Name: count, dtype: int64

#### 데이터 전처리

In [14]:
m = train['OCCUPATION_TYPE'].mode()[0]
train['OCCUPATION_TYPE'] = train['OCCUPATION_TYPE'].fillna(m)
test['OCCUPATION_TYPE'] = test['OCCUPATION_TYPE'].fillna(m)

In [15]:
#컬럼(ID) 삭제
train = train.drop('ID', axis=1)
test = test.drop('ID', axis=1)

In [18]:
#인코딩
obj_cols = train.select_dtypes(include='O').columns

for col in obj_cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

In [20]:
#검증 데이터 나누기
x_train,x_val, y_train, y_val = train_test_split(
    train,
    target,
    test_size=0.2,
    random_state=0,
)

print('x_train :', x_train.shape)
print('x_val :', x_val.shape)
print('y_train :', y_train.shape)
print('y_val :', y_val.shape)

x_train : (20415, 17)
x_val : (5104, 17)
y_train : (20415,)
y_val : (5104,)

### 학습 및 평가

In [22]:
model = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=0)
model.fit(x_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=0)

In [23]:
pred = model.predict(x_val)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
#평가
f1 = f1_score(y_val, pred)
print("f1 :", f1)

f1 : 0.3253968253968254

In [26]:
pred = model.predict(test)
submit = pd.DataFrame({'pred' : pred})
submit.to_csv('credit_result.csv', index=False)
submit.head()

   pred
0     0
1     0
2     0
3     0
4     0